# Generated by Django 5.0.1 on 2024-01-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('TD', 'Todo'), ('IP', 'In progress'), ('FN', 'Finished')], default='TD', max_length=2)),
            ],
        ),
    ]
